name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.0
      - run: ./build-win.ps1
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.0
      - run: sudo apt install -y clang
      - run: ./build-linux.sh
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.0
      - run: ./build-macos.sh
